window.JOKES = [

  "I tried to read a book on anti-gravity. I couldn’t put it down.",
  "Parallel lines have so much in common. It’s a shame they’ll never meet.",
  "Why don’t scientists trust atoms? Because they make up everything.",
  "I would tell you a joke about time travel, but you didn’t like it.",
  "Why did the scarecrow win an award? He was outstanding in his field.",
  "I used to play piano by ear. Now I use my hands.",
  "Why don’t skeletons fight each other? They don’t have the guts.",
  "I’m reading a book about teleportation. It’s bound to take me places.",
  "What do you call fake spaghetti? An impasta.",
  "Why did the math book look sad? It had too many problems.",
  "Why don’t eggs tell jokes? They’d crack each other up.",
  "I told my wife she was drawing her eyebrows too high. She looked surprised.",
  "I used to be afraid of hurdles, but I got over it.",
  "What do you call cheese that isn’t yours? Nacho cheese.",
  "Why can’t your nose be 12 inches long? Because then it would be a foot.",
  "I once got fired from a keyboard factory. I wasn’t putting in enough shifts.",
  "I asked the librarian if the library had books on paranoia. She whispered, “They’re right behind you.”",
  "What do you call a belt made of watches? A waist of time.",
  "What did 0 say to 8? Nice belt.",
  "Why did the stadium get hot after the game? All the fans left.",
  "Why did the cookie go to the hospital? It felt crummy.",
  "Why don’t seagulls fly over the bay? Because then they’d be bagels.",
  "Why are ghosts bad liars? You can see right through them.",
  "What did one wall say to the other? I’ll meet you at the corner.",
  "Why don’t sharks eat clowns? They taste funny.",
  "What do you call an alien with three eyes? An aliiien.",
  "What’s an alien’s favorite music? Neptunes.",
  "Why did the astronaut break up with his girlfriend? He needed space.",
  "I only know 25 letters of the alphabet. I don’t know y.",
  "I’m on a seafood diet. I see food and I eat it.",
  "I told my computer I needed a break. It said, 'No problem, I’ll go to sleep.'",
  "I would avoid the sushi if I were you. It’s a little fishy.",
  "I used to hate facial hair, but then it grew on me.",
  "Why can’t you hear a pterodactyl go to the bathroom? Because the P is silent.",
  "I’m afraid for the calendar. Its days are numbered.",
  "I told my dog a chemistry joke. There was no reaction.",
  "I only buy velcro. I can’t deal with ties.",
  "Why don’t oysters donate to charity? Because they’re shellfish.",
  "I once got fired from a canned juice company. I couldn’t concentrate.",
  "Why did the bicycle fall over? It was two-tired.",
  "I ordered a chicken and an egg online. I’ll let you know.",
  "Why did the coffee file a police report? It got mugged.",
  "I told my suitcase there would be no vacations this year. Now I’m dealing with emotional baggage.",
  "Why don’t programmers like nature? Too many bugs.",
  "I tried to catch fog yesterday. Mist.",
  "Why did the golfer bring two pairs of pants? In case he got a hole in one.",
  "Why don’t crabs give to charity? Because they’re shellfish.",
  "I used to be addicted to soap. I’m clean now.",
  "I told my wife she should embrace her mistakes. She hugged me.",
  "I once had a job at a bakery. I kneaded dough.",
  "Why did the invisible man turn down the job offer? He couldn’t see himself doing it.",
  "Why don’t melons get married? Because they cantaloupe.",
  "I accidentally swallowed some food coloring. I feel like I’ve dyed a little inside.",
  "Did you hear about the antennas that got married? The reception was fantastic!",
  "I went to buy some camouflage pants, but I couldn’t find any.",
  "I told my doctor I broke my arm in two places. He told me to stop going to those places.",
  "I tried to sue the airport for losing my luggage. I lost my case.",
  "I used to be addicted to the hokey pokey, but I turned myself around.",
  "I used to work in a shoe recycling shop. It was sole-destroying.",
  "I used to be a banker, but I lost interest.",
  "I once worked at a blanket factory. It folded.",
  "I don’t trust stairs. They’re always up to something.",
  "I used to be a watchmaker. It was about time.",
  "I once had a job at a calendar factory, but I took a couple days off.",
  "I told my friend 10 jokes to make him laugh. Sadly, no pun in ten did.",
  "I bought a ceiling fan. Complete waste of money. He just stands there applauding.",
  "I used to be a lumberjack, but I couldn’t hack it.",
  "I once worked at a coffee shop. I had to espresso myself.",
  "I tried to be a ghost, but I didn’t have the spirit.",
  "I once worked in a glue factory. I couldn’t stick with it.",
  "I tried to write a joke about paper, but it was tearable.",
  "I used to be a math teacher, but I lost my class.",
  "I once worked at a sunglasses factory. It was shady.",
  "I used to be a tailor, but I wasn’t suited for it.",
  "I once worked at a mirror factory. I could really see myself there.",
  "I told my wife she should do lunges to stay in shape. That would be a big step forward.",
  "I once worked at a battery factory. I got charged.",
  "I tried to write a joke about construction, but I’m still working on it.",
  "I once worked at a bakery. The business was crumbling.",
  "Did you hear about the circus fire? It was in tents!",
  "How do you catch a squirrel? Climb a tree and act like a nut!",
  "Did you hear about the guy who invented Lifesavers? They say he made a mint!",
  "What did the big flower say to the little flower? Hi, bud!",
  "What did the grape say when it got stepped on? Nothing, it just let out a little wine.",
  "What do you call a snowman with a six-pack? An abdominal snowman!",
  "Did you hear about the restaurant on the moon? Great food, no atmosphere!",
  "What did one hat say to the other hat? You stay here, I’ll go on ahead!",
  "Did you hear about the guy who got hit in the head with a can of soda? He was lucky it was a soft drink.",
  "I’m writing a book about glue, but I’m stuck on the first chapter.",
  "What did one plate whisper to the other plate? Dinner is on me.",
  "Try the seafood diet. You see food, then you eat it.",
  "Did you hear the rumor about butter? Well, I’m not going to go spreading it!",
  "What’s Forrest Gump’s password? 1forrest1",
  "What state is known for its small drinks? Minnesota.",
  "What does a nosey pepper do? It gets jalapeño business.",
  "If two vegetarians get in an argument, is it still called beef?",
  "I have a clean conscience. It’s never been used.",
  "I love telling dad jokes. Sometimes, he even laughs.",
  "How do you stop a bull from charging? Cancel its credit card.",
  "What’s the difference between a man’s wallet before and after kids? There are pictures where the money used to be.",
  "How do you follow Will Smith in the mud? Follow the fresh prints.",
  "My kid is blaming me for ruining their birthday. That’s ridiculous. I didn’t even know it was today.",
  "What’s the difference between the bird flu and the swine flu? One requires tweetment and the other an oinkment.",
  "What do you call a line of men waiting to get haircuts? A barberqueue.",
  "What do you call two monkeys who share an Amazon Prime account? Prime mates.",
  "Why can’t a leopard hide? He’s always spotted.",
  "Air used to be free at the gas station. Now it costs 2.50. Inflation.",
  "Did you hear about the claustrophobic astronaut? He just needed a little space.",
  "Why did the orange lose the race? It ran out of juice.",
  "How do you fix a broken pumpkin? With a pumpkin patch.",
  "What’s the best thing about Switzerland? I don’t know, but the flag is a big plus.",
  "Why did the man fall down the well? Because he couldn’t see that well.",
  "What has ears but cannot hear? A cornfield.",
  "Can February March? No, but April May.",
  "Why was six afraid of seven? Because seven ate nine.",
  "What do you call a pencil with two erasers? Pointless.",
  "What’s brown and sticky? A stick.",
  "It really takes guts to be an organ donor.",
  "Why’d the fisherman order the halibut? Just for the halibut.",
  "Why is Peter Pan always flying? Because he Neverlands.",
  "How do you throw a party in outer space? You planet.",
  "How do you make an octopus laugh? With ten-tickles.",
  "What type of tree fits in your hand? A palm tree.",
  "How does a lawyer say goodbye? I’ll be suing ya.",
  "What made the tomato blush? It saw the salad dressing.",
  "What do you call a sleeping bull? A bulldozer.",
  "Why do bees have sticky hair? Because they use a honeycomb.",
  "What do you call a fibbing cat? A lion.",
  "If a child refuses to nap, are they guilty of resisting a rest?",
  "RIP boiling water, you will be mist.",
  "I ate a clock the other day. It was very time consuming.",
  "You can tell it’s a dogwood tree from its bark.",
  "When does a joke turn into a dad joke? When it becomes apparent.",
  "They say that three out of two people are bad at fractions.",
  "Why did the picture go to prison? Because it was framed.",
  "What gets wetter the more it dries? A towel.",
  "I was wondering why the frisbee kept getting bigger and bigger. Then it hit me.",
  "What do you call someone who tells dad jokes but isn’t a dad? A faux pa.",
  "If you see a crime at an Apple store, are you an iWitness?",
  "Why are spiders so smart? They can find everything on the web.",
  "What do you call a toothless bear? A gummy bear.",
  "What do you give a sick lemon? Lemon-aid.",
  "What kind of car does a sheep like to drive? A lamborghini.",
  "What key is used to open bananas? A mon-key.",
  "What has four wheels and flies? A garbage truck.",
  "How do you make a tissue dance? Put a little boogie in it.",
  "What do you call an alligator in a vest? An investigator."

];
