// 40 unique, pickable symbols (faces + life stuff).
window.SYMBOLS = [
  { key:"happy", symbol:"😊", name:"Happy" },
  { key:"meh", symbol:"😐", name:"Meh" },
  { key:"rage", symbol:"😡", name:"Rage" },
  { key:"frustrated", symbol:"😤", name:"Frustrated" },
  { key:"anxious", symbol:"😰", name:"Anxious" },
  { key:"tired", symbol:"😴", name:"Tired" },
  { key:"hopeful", symbol:"🤞", name:"Hopeful" },
  { key:"confident", symbol:"😎", name:"Confident" },
  { key:"overwhelmed", symbol:"🤯", name:"Overwhelmed" },
  { key:"nervous", symbol:"😬", name:"Nervous" },
  { key:"excited", symbol:"🥳", name:"Excited" },
  { key:"nauseous", symbol:"🤢", name:"Nauseous" },
  { key:"cat", symbol:"🐱", name:"Cat" },
  { key:"goofy", symbol:"🤪", name:"Goofy" },
  { key:"devilish", symbol:"😈", name:"Devilish" },
  { key:"melting", symbol:"🫠", name:"Melting" },
  { key:"hearteyes", symbol:"😍", name:"Heart Eyes" },
  { key:"frazzled", symbol:"😵‍💫", name:"Frazzled" },
  { key:"shrug", symbol:"🤷", name:"Shrug" },
  { key:"cry", symbol:"🥹", name:"Soft" },

  { key:"dog", symbol:"🐶", name:"Dog" },
  { key:"coffee", symbol:"☕", name:"Coffee" },
  { key:"home", symbol:"🏠", name:"Home" },
  { key:"money", symbol:"💰", name:"Money" },
  { key:"heart", symbol:"❤️", name:"Love" },
  { key:"plant", symbol:"🌱", name:"Growth" },
  { key:"star", symbol:"⭐", name:"Star" },
  { key:"sparkles", symbol:"✨", name:"Sparkles" },
  { key:"clover", symbol:"🍀", name:"Clover" },
  { key:"moon", symbol:"🌙", name:"Moon" },
  { key:"sun", symbol:"🌞", name:"Sun" },
  { key:"rainbow", symbol:"🌈", name:"Rainbow" },
  { key:"gift", symbol:"🎁", name:"Gift" },
  { key:"music", symbol:"🎵", name:"Music" },
  { key:"book", symbol:"📚", name:"Books" },
  { key:"camera", symbol:"📷", name:"Camera" },
  { key:"running", symbol:"🏃", name:"Run" },
  { key:"dance", symbol:"💃", name:"Dance" },
  { key:"pizza", symbol:"🍕", name:"Pizza" },
  { key:"sleep", symbol:"🛌", name:"Sleep" }
];
