// symbols.js
// 100 unique, fixed-position symbols.
// Exposes: window.SYMBOLS = [{ name, symbol }, ...]

(function () {
  window.SYMBOLS = [
    { name:"Star", symbol:"⭐" },
    { name:"Sparkles", symbol:"✨" },
    { name:"Glowing star", symbol:"🌟" },
    { name:"Moon", symbol:"🌙" },
    { name:"Sun", symbol:"☀️" },
    { name:"Cloud", symbol:"☁️" },
    { name:"Rainbow", symbol:"🌈" },
    { name:"Lightning", symbol:"⚡" },
    { name:"Snowflake", symbol:"❄️" },
    { name:"Umbrella", symbol:"☂️" },

    { name:"Clover", symbol:"🍀" },
    { name:"Horseshoe", symbol:"🧲" }, /* simple stand-in, can swap */
    { name:"Heart", symbol:"❤️" },
    { name:"Broken heart", symbol:"💔" },
    { name:"Fire", symbol:"🔥" },
    { name:"Droplet", symbol:"💧" },
    { name:"Leaf", symbol:"🍃" },
    { name:"Flower", symbol:"🌸" },
    { name:"Rose", symbol:"🌹" },
    { name:"Seedling", symbol:"🌱" },

    { name:"Cat", symbol:"🐈" },
    { name:"Dog", symbol:"🐕" },
    { name:"Rabbit", symbol:"🐇" },
    { name:"Fox", symbol:"🦊" },
    { name:"Bear", symbol:"🐻" },
    { name:"Owl", symbol:"🦉" },
    { name:"Butterfly", symbol:"🦋" },
    { name:"Bee", symbol:"🐝" },
    { name:"Turtle", symbol:"🐢" },
    { name:"Fish", symbol:"🐟" },

    { name:"Coffee", symbol:"☕" },
    { name:"Tea", symbol:"🫖" },
    { name:"Pizza", symbol:"🍕" },
    { name:"Donut", symbol:"🍩" },
    { name:"Apple", symbol:"🍎" },
    { name:"Cookie", symbol:"🍪" },
    { name:"Cake", symbol:"🎂" },
    { name:"Cherry", symbol:"🍒" },
    { name:"Lemon", symbol:"🍋" },
    { name:"Popcorn", symbol:"🍿" },

    { name:"Book", symbol:"📘" },
    { name:"Pencil", symbol:"✏️" },
    { name:"Paint palette", symbol:"🎨" },
    { name:"Camera", symbol:"📷" },
    { name:"Music note", symbol:"🎵" },
    { name:"Headphones", symbol:"🎧" },
    { name:"Microphone", symbol:"🎤" },
    { name:"Game die", symbol:"🎲" },
    { name:"Ticket", symbol:"🎟️" },
    { name:"Trophy", symbol:"🏆" },

    { name:"Key", symbol:"🔑" },
    { name:"Lock", symbol:"🔒" },
    { name:"Compass", symbol:"🧭" },
    { name:"Map", symbol:"🗺️" },
    { name:"Magnifying glass", symbol:"🔎" },
    { name:"Light bulb", symbol:"💡" },
    { name:"Hourglass", symbol:"⏳" },
    { name:"Clock", symbol:"🕰️" },
    { name:"Phone", symbol:"📱" },
    { name:"Laptop", symbol:"💻" },

    { name:"Rocket", symbol:"🚀" },
    { name:"Airplane", symbol:"✈️" },
    { name:"Car", symbol:"🚗" },
    { name:"Bicycle", symbol:"🚲" },
    { name:"Train", symbol:"🚆" },
    { name:"Boat", symbol:"⛵" },
    { name:"Backpack", symbol:"🎒" },
    { name:"Suitcase", symbol:"🧳" },
    { name:"Tent", symbol:"⛺" },
    { name:"Mountain", symbol:"⛰️" },

    { name:"Handshake", symbol:"🤝" },
    { name:"Thumbs up", symbol:"👍" },
    { name:"Peace", symbol:"✌️" },
    { name:"Clap", symbol:"👏" },
    { name:"Muscle", symbol:"💪" },
    { name:"Brain", symbol:"🧠" },
    { name:"Eyes", symbol:"👀" },
    { name:"Mouth", symbol:"👄" },
    { name:"Footprints", symbol:"👣" },
    { name:"Spark", symbol:"💥" },

    { name:"Gift", symbol:"🎁" },
    { name:"Balloon", symbol:"🎈" },
    { name:"Party popper", symbol:"🎉" },
    { name:"Confetti ball", symbol:"🎊" },
    { name:"Crystal ball", symbol:"🔮" },
    { name:"Gem", symbol:"💎" },
    { name:"Crown", symbol:"👑" },
    { name:"Shield", symbol:"🛡️" },
    { name:"Anchor", symbol:"⚓" },
    { name:"Dice again", symbol:"🎰" } /* stand-in, can swap */
  ];
})();
