// watchlist.js
// Feeds the “What should I watch?” spinner

window.WATCHLIST = [
  { title: "1917", type: "Movie", year: "2019" },
  { title: "A Beautiful Mind", type: "Movie", year: "2001" },
  { title: "A Quiet Place", type: "Movie", year: "2018" },
  { title: "About Time", type: "Movie", year: "2013" },
  { title: "Air", type: "Movie", year: "2023" },
  { title: "Airplane!", type: "Movie", year: "1980" },
  { title: "Alien", type: "Movie", year: "1979" },
  { title: "All the President's Men", type: "Movie", year: "1976" },
  { title: "Almost Famous", type: "Movie", year: "2000" },
  { title: "American Psycho", type: "Movie", year: "2000" },
  { title: "Amélie", type: "Movie", year: "2001" },
  { title: "Anchorman: The Legend of Ron Burgundy", type: "Movie", year: "2004" },
  { title: "Another Round", type: "Movie", year: "2020" },
  { title: "Apocalypse Now", type: "Movie", year: "1979" },
  { title: "Apollo 13", type: "Movie", year: "1995" },
  { title: "Argo", type: "Movie", year: "2012" },
  { title: "Arrival", type: "Movie", year: "2016" },

  { title: "Back to the Future", type: "Movie", year: "1985" },
  { title: "Band of Brothers", type: "TV", year: "2001" },
  { title: "Barbie", type: "Movie", year: "2023" },
  { title: "Beetlejuice", type: "Movie", year: "1988" },
  { title: "Before Sunrise", type: "Movie", year: "1995" },
  { title: "Belfast", type: "Movie", year: "2021" },
  { title: "Better Call Saul", type: "TV", year: "2015–2022" },
  { title: "Big", type: "Movie", year: "1988" },
  { title: "Big Little Lies", type: "TV", year: "2017–2019" },
  { title: "Birdman", type: "Movie", year: "2014" },
  { title: "Black Hawk Down", type: "Movie", year: "2001" },
  { title: "Black Mirror", type: "TV", year: "2011–2023" },
  { title: "Blade Runner", type: "Movie", year: "1982" },
  { title: "Blade Runner 2049", type: "Movie", year: "2017" },
  { title: "Boardwalk Empire", type: "TV", year: "2010–2014" },
  { title: "Borat", type: "Movie", year: "2006" },
  { title: "Braveheart", type: "Movie", year: "1995" },
  { title: "Bridesmaids", type: "Movie", year: "2011" },
  { title: "Brokeback Mountain", type: "Movie", year: "2005" },
  { title: "Butch Cassidy and the Sundance Kid", type: "Movie", year: "1969" },

  { title: "Caddyshack", type: "Movie", year: "1980" },
  { title: "Call Me by Your Name", type: "Movie", year: "2017" },
  { title: "Casino Royale", type: "Movie", year: "2006" },
  { title: "Catch Me If You Can", type: "Movie", year: "2002" },
  { title: "Chernobyl", type: "TV", year: "2019" },
  { title: "Chicago", type: "Movie", year: "2002" },
  { title: "Chinatown", type: "Movie", year: "1974" },
  { title: "Clueless", type: "Movie", year: "1995" },
  { title: "Close Encounters of the Third Kind", type: "Movie", year: "1977" },
  { title: "Coco", type: "Movie", year: "2017" },
  { title: "Coming to America", type: "Movie", year: "1988" },
  { title: "Cool Hand Luke", type: "Movie", year: "1967" },
  { title: "Crash", type: "Movie", year: "2004" },
  { title: "Crazy, Stupid, Love.", type: "Movie", year: "2011" },
  { title: "Crazy Rich Asians", type: "Movie", year: "2018" },
  { title: "Crouching Tiger, Hidden Dragon", type: "Movie", year: "2000" },

  { title: "Dallas Buyers Club", type: "Movie", year: "2013" },
  { title: "Date Night", type: "Movie", year: "2010" },
  { title: "Dances with Wolves", type: "Movie", year: "1990" },
  { title: "Dazed and Confused", type: "Movie", year: "1993" },
  { title: "Dead Poets Society", type: "Movie", year: "1989" },
  { title: "Death Proof", type: "Movie", year: "2007" },
  { title: "Die Hard", type: "Movie", year: "1988" },
  { title: "Donnie Brasco", type: "Movie", year: "1997" },
  { title: "Donnie Darko", type: "Movie", year: "2001" },
  { title: "Drive", type: "Movie", year: "2011" },
  { title: "Django Unchained", type: "Movie", year: "2012" },
  { title: "Dunkirk", type: "Movie", year: "2017" },
  { title: "Dune", type: "Movie", year: "2021" },
  { title: "Dune: Part Two", type: "Movie", year: "2024" },

  { title: "E.T. the Extra-Terrestrial", type: "Movie", year: "1982" },
  { title: "Elvis", type: "Movie", year: "2022" },
  { title: "Enter the Dragon", type: "Movie", year: "1973" },
  { title: "Entourage", type: "TV", year: "2004–2011" },
  { title: "Eternal Sunshine of the Spotless Mind", type: "Movie", year: "2004" },
  { title: "Everything Everywhere All at Once", type: "Movie", year: "2022" },
  { title: "Ex Machina", type: "Movie", year: "2014" },
  { title: "The Exorcist", type: "Movie", year: "1973" },

  { title: "Fargo", type: "Movie", year: "1996" },
  { title: "Fargo", type: "TV", year: "2014–2024" },
  { title: "Ferris Bueller's Day Off", type: "Movie", year: "1986" },
  { title: "Finding Nemo", type: "Movie", year: "2003" },
  { title: "Fight Club", type: "Movie", year: "1999" },
  { title: "Forrest Gump", type: "Movie", year: "1994" },
  { title: "Friday", type: "Movie", year: "1995" },
  { title: "Friends", type: "TV", year: "1994–2004" },
  { title: "Full Metal Jacket", type: "Movie", year: "1987" },

  { title: "Game of Thrones", type: "TV", year: "2011–2019" },
  { title: "Get Out", type: "Movie", year: "2017" },
  { title: "Ghostbusters", type: "Movie", year: "1984" },
  { title: "Gladiator", type: "Movie", year: "2000" },
  { title: "Glass Onion", type: "Movie", year: "2022" },
  { title: "The Godfather", type: "Movie", year: "1972" },
  { title: "The Godfather Part II", type: "Movie", year: "1974" },
  { title: "Goodfellas", type: "Movie", year: "1990" },
  { title: "Good Will Hunting", type: "Movie", year: "1997" },
  { title: "Groundhog Day", type: "Movie", year: "1993" },

  { title: "Hacksaw Ridge", type: "Movie", year: "2016" },
  { title: "The Hateful Eight", type: "Movie", year: "2015" },
  { title: "Heat", type: "Movie", year: "1995" },
  { title: "Her", type: "Movie", year: "2013" },
  { title: "High Noon", type: "Movie", year: "1952" },
  { title: "The Holdovers", type: "Movie", year: "2023" },
  { title: "Home Alone", type: "Movie", year: "1990" },

  { title: "Inception", type: "Movie", year: "2010" },
  { title: "Indiana Jones and the Raiders of the Lost Ark", type: "Movie", year: "1981" },
  { title: "Inglourious Basterds", type: "Movie", year: "2009" },
  { title: "Inside Out", type: "Movie", year: "2015" },
  { title: "Interstellar", type: "Movie", year: "2014" },

  { title: "Jackie Brown", type: "Movie", year: "1997" },
  { title: "Jaws", type: "Movie", year: "1975" },
  { title: "Jerry Maguire", type: "Movie", year: "1996" },
  { title: "John Wick", type: "Movie", year: "2014" },
  { title: "Jurassic Park", type: "Movie", year: "1993" },

  { title: "Kill Bill: Vol. 1", type: "Movie", year: "2003" },
  { title: "Kill Bill: Vol. 2", type: "Movie", year: "2004" },
  { title: "Knives Out", type: "Movie", year: "2019" },

  { title: "La La Land", type: "Movie", year: "2016" },
  { title: "The Lord of the Rings: The Fellowship of the Ring", type: "Movie", year: "2001" },
  { title: "The Lord of the Rings: The Return of the King", type: "Movie", year: "2003" },

  { title: "Mad Men", type: "TV", year: "2007–2015" },
  { title: "Marriage Story", type: "Movie", year: "2019" },
  { title: "Mean Girls", type: "Movie", year: "2004" },
  { title: "Moneyball", type: "Movie", year: "2011" },

  { title: "Napoleon Dynamite", type: "Movie", year: "2004" },
  { title: "No Country for Old Men", type: "Movie", year: "2007" },

  { title: "Ocean's Eleven", type: "Movie", year: "2001" },
  { title: "Once Upon a Time in Hollywood", type: "Movie", year: "2019" },
  { title: "Oppenheimer", type: "Movie", year: "2023" },

  { title: "Parasite", type: "Movie", year: "2019" },
  { title: "Patton", type: "Movie", year: "1970" },
  { title: "Platoon", type: "Movie", year: "1986" },
  { title: "Pulp Fiction", type: "Movie", year: "1994" },

  { title: "Raging Bull", type: "Movie", year: "1980" },
  { title: "Reservoir Dogs", type: "Movie", year: "1992" },
  { title: "Rocky", type: "Movie", year: "1976" },

  { title: "Saving Private Ryan", type: "Movie", year: "1998" },
  { title: "Schitt's Creek", type: "TV", year: "2015–2020" },
  { title: "Seinfeld", type: "TV", year: "1989–1998" },
  { title: "Seven", type: "Movie", year: "1995" },
  { title: "Sex and the City", type: "TV", year: "1998–2004" },
  { title: "The Shawshank Redemption", type: "Movie", year: "1994" },
  { title: "Sicario", type: "Movie", year: "2015" },
  { title: "Spotlight", type: "Movie", year: "2015" },
  { title: "Star Wars: A New Hope", type: "Movie", year: "1977" },
  { title: "Stranger Things", type: "TV", year: "2016–2025" },
  { title: "Succession", type: "TV", year: "2018–2023" },
  { title: "Superbad", type: "Movie", year: "2007" },

  { title: "Taskmaster", type: "TV", year: "2015–" },
  { title: "Ted Lasso", type: "TV", year: "2020–2023" },
  { title: "The Big Lebowski", type: "Movie", year: "1998" },
  { title: "The Departed", type: "Movie", year: "2006" },
  { title: "The Matrix", type: "Movie", year: "1999" },
  { title: "The Prestige", type: "Movie", year: "2006" },
  { title: "The Princess Bride", type: "Movie", year: "1987" },
  { title: "The Sopranos", type: "TV", year: "1999–2007" },
  { title: "The Truman Show", type: "Movie", year: "1998" },
  { title: "The White Lotus", type: "TV", year: "2021–2025" },
  { title: "The Wire", type: "TV", year: "2002–2008" },

  { title: "Titanic", type: "Movie", year: "1997" },
  { title: "Top Gun", type: "Movie", year: "1986" },
  { title: "Top Gun: Maverick", type: "Movie", year: "2022" },
  { title: "Toy Story", type: "Movie", year: "1995" },

  { title: "Unforgiven", type: "Movie", year: "1992" },
  { title: "Veep", type: "TV", year: "2012–2019" },
  { title: "Whiplash", type: "Movie", year: "2014" },
  { title: "When Harry Met Sally…", type: "Movie", year: "1989" },
  { title: "Zodiac", type: "Movie", year: "2007" }
];
