// watchlist.js
// Feeds the “What should I watch?” spinner
// Rules: alphabetical by title, no duplicates, title/type/year only

export const watchlist = [
  { title: "1917", type: "Movie", year: "2019" },
  { title: "A Beautiful Mind", type: "Movie", year: "2001" },
  { title: "A Quiet Place", type: "Movie", year: "2018" },
  { title: "About Time", type: "Movie", year: "2013" },
  { title: "Air", type: "Movie", year: "2023" },
  { title: "Airplane!", type: "Movie", year: "1980" },
  { title: "Alien", type: "Movie", year: "1979" },
  { title: "All the President's Men", type: "Movie", year: "1976" },
  { title: "Almost Famous", type: "Movie", year: "2000" },
  { title: "American Psycho", type: "Movie", year: "2000" },
  { title: "Amélie", type: "Movie", year: "2001" },
  { title: "Anchorman: The Legend of Ron Burgundy", type: "Movie", year: "2004" },
  { title: "Another Round", type: "Movie", year: "2020" },
  { title: "Apocalypse Now", type: "Movie", year: "1979" },
  { title: "Apollo 13", type: "Movie", year: "1995" },
  { title: "Argo", type: "Movie", year: "2012" },
  { title: "Arrival", type: "Movie", year: "2016" },
  { title: "As Good as It Gets", type: "Movie", year: "1997" },
  { title: "A Star Is Born", type: "Movie", year: "2018" },

  { title: "Back to the Future", type: "Movie", year: "1985" },
  { title: "Band of Brothers", type: "TV", year: "2001" },
  { title: "Barbarian", type: "Movie", year: "2022" },
  { title: "Barbie", type: "Movie", year: "2023" },
  { title: "Beetlejuice", type: "Movie", year: "1988" },
  { title: "Before Sunrise", type: "Movie", year: "1995" },
  { title: "Belfast", type: "Movie", year: "2021" },
  { title: "Better Call Saul", type: "TV", year: "2015–2022" },
  { title: "Big", type: "Movie", year: "1988" },
  { title: "Big Little Lies", type: "TV", year: "2017–2019" },
  { title: "Birdman", type: "Movie", year: "2014" },
  { title: "Black Hawk Down", type: "Movie", year: "2001" },
  { title: "Black Mirror", type: "TV", year: "2011–" },
  { title: "Black Swan", type: "Movie", year: "2010" },
  { title: "Blade Runner", type: "Movie", year: "1982" },
  { title: "Blade Runner 2049", type: "Movie", year: "2017" },
  { title: "Boardwalk Empire", type: "TV", year: "2010–2014" },
  { title: "Borat", type: "Movie", year: "2006" },
  { title: "Braveheart", type: "Movie", year: "1995" },
  { title: "Bridesmaids", type: "Movie", year: "2011" },
  { title: "Brokeback Mountain", type: "Movie", year: "2005" },
  { title: "Butch Cassidy and the Sundance Kid", type: "Movie", year: "1969" },

  { title: "Caddyshack", type: "Movie", year: "1980" },
  { title: "Call Me by Your Name", type: "Movie", year: "2017" },
  { title: "Casino Royale", type: "Movie", year: "2006" },
  { title: "Catch Me If You Can", type: "Movie", year: "2002" },
  { title: "Chernobyl", type: "TV", year: "2019" },
  { title: "Cheech & Chong's Up in Smoke", type: "Movie", year: "1978" },
  { title: "Chicago", type: "Movie", year: "2002" },
  { title: "Chinatown", type: "Movie", year: "1974" },
  { title: "Clerks", type: "Movie", year: "1994" },
  { title: "Clueless", type: "Movie", year: "1995" },
  { title: "Close Encounters of the Third Kind", type: "Movie", year: "1977" },
  { title: "Coco", type: "Movie", year: "2017" },
  { title: "Coming to America", type: "Movie", year: "1988" },
  { title: "Cool Hand Luke", type: "Movie", year: "1967" },
  { title: "Crash", type: "Movie", year: "2004" },
  { title: "Crazy, Stupid, Love.", type: "Movie", year: "2011" },
  { title: "Crazy Rich Asians", type: "Movie", year: "2018" },
  { title: "Crouching Tiger, Hidden Dragon", type: "Movie", year: "2000" },

  { title: "Dallas Buyers Club", type: "Movie", year: "2013" },
  { title: "Date Night", type: "Movie", year: "2010" },
  { title: "Dances with Wolves", type: "Movie", year: "1990" },
  { title: "Dazed and Confused", type: "Movie", year: "1993" },
  { title: "Dead Poets Society", type: "Movie", year: "1989" },
  { title: "Death Proof", type: "Movie", year: "2007" },
  { title: "Die Hard", type: "Movie", year: "1988" },
  { title: "Donnie Brasco", type: "Movie", year: "1997" },
  { title: "Donnie Darko", type: "Movie", year: "2001" },
  { title: "Drive", type: "Movie", year: "2011" },
  { title: "Django Unchained", type: "Movie", year: "2012" },
  { title: "Dunkirk", type: "Movie", year: "2017" },
  { title: "Dune", type: "Movie", year: "2021" },
  { title: "Dune: Part Two", type: "Movie", year: "2024" },

  { title: "E.T. the Extra-Terrestrial", type: "Movie", year: "1982" },
  { title: "Elvis", type: "Movie", year: "2022" },
  { title: "Enter the Dragon", type: "Movie", year: "1973" },
  { title: "Entourage", type: "TV", year: "2004–2011" },
  { title: "Eternal Sunshine of the Spotless Mind", type: "Movie", year: "2004" },
  { title: "Everything Everywhere All at Once", type: "Movie", year: "2022" },
  { title: "Ex Machina", type: "Movie", year: "2014" },
  { title: "The Exorcist", type: "Movie", year: "1973" },

  { title: "Fargo", type: "Movie", year: "1996" },
  { title: "Fargo", type: "TV", year: "2014–" },
  { title: "Ferris Bueller's Day Off", type: "Movie", year: "1986" },
  { title: "Finding Nemo", type: "Movie", year: "2003" },
  { title: "Fight Club", type: "Movie", year: "1999" },
  { title: "Flashdance", type: "Movie", year: "1983" },
  { title: "Footloose", type: "Movie", year: "1984" },
  { title: "Forrest Gump", type: "Movie", year: "1994" },
  { title: "Free Guy", type: "Movie", year: "2021" },
  { title: "Friday", type: "Movie", year: "1995" },
  { title: "Friends", type: "TV", year: "1994–2004" },
  { title: "Full Metal Jacket", type: "Movie", year: "1987" },
  { title: "The French Connection", type: "Movie", year: "1971" },

  { title: "Game of Thrones", type: "TV", year: "2011–2019" },
  { title: "Get Out", type: "Movie", year: "2017" },
  { title: "Ghostbusters", type: "Movie", year: "1984" },
  { title: "Girls", type: "TV", year: "2012–2017" },
  { title: "Gladiator", type: "Movie", year: "2000" },
  { title: "Glass Onion", type: "Movie", year: "2022" },
  { title: "The Godfather", type: "Movie", year: "1972" },
  { title: "The Godfather Part II", type: "Movie", year: "1974" },
  { title: "Godzilla Minus One", type: "Movie", year: "2023" },
  { title: "Gone Girl", type: "Movie", year: "2014" },
  { title: "Goodfellas", type: "Movie", year: "1990" },
  { title: "Good Morning, Vietnam", type: "Movie", year: "1987" },
  { title: "Good Will Hunting", type: "Movie", year: "1997" },
  { title: "Gravity", type: "Movie", year: "2013" },
  { title: "The Great Escape", type: "Movie", year: "1963" },
  { title: "The Great Gatsby", type: "Movie", year: "2013" },
  { title: "The Green Mile", type: "Movie", year: "1999" },
  { title: "Grease", type: "Movie", year: "1978" },
  { title: "Groundhog Day", type: "Movie", year: "1993" },

  { title: "Half Baked", type: "Movie", year: "1998" },
  { title: "Hacksaw Ridge", type: "Movie", year: "2016" },
  { title: "The Hateful Eight", type: "Movie", year: "2015" },
  { title: "Harry Potter and the Sorcerer's Stone", type: "Movie", year: "2001" },
  { title: "Heat", type: "Movie", year: "1995" },
  { title: "Her", type: "Movie", year: "2013" },
  { title: "High Noon", type: "Movie", year: "1952" },
  { title: "The Holdovers", type: "Movie", year: "2023" },
  { title: "Home Alone", type: "Movie", year: "1990" },

  { title: "Inception", type: "Movie", year: "2010" },
  { title: "Indiana Jones and the Last Crusade", type: "Movie", year: "1989" },
  { title: "Indiana Jones and the Raiders of the Lost Ark", type: "Movie", year: "1981" },
  { title: "Inglourious Basterds", type: "Movie", year: "2009" },
  { title: "Inside Out", type: "Movie", year: "2015" },
  { title: "Interstellar", type: "Movie", year: "2014" },
  { title: "Jackie Brown", type: "Movie", year: "1997" },
  { title: "Jarhead", type: "Movie", year: "2005" },
  { title: "Jaws", type: "Movie", year: "1975" },
  { title: "Jerry Maguire", type: "Movie", year: "1996" },
  { title: "John Wick", type: "Movie", year: "2014" },
  { title: "Jojo Rabbit", type: "Movie", year: "2019" },
  { title: "Jurassic Park", type: "Movie", year: "1993" },

  { title: "Karate Kid", type: "Movie", year: "1984" },
  { title: "King Richard", type: "Movie", year: "2021" },
  { title: "Knives Out", type: "Movie", year: "2019" },
  { title: "Knocked Up", type: "Movie", year: "2007" },
  { title: "Kramer vs. Kramer", type: "Movie", year: "1979" },
  { title: "Kill Bill: Vol. 1", type: "Movie", year: "2003" },
  { title: "Kill Bill: Vol. 2", type: "Movie", year: "2004" },

  { title: "L.A. Confidential", type: "Movie", year: "1997" },
  { title: "La La Land", type: "Movie", year: "2016" },
  { title: "Lady Bird", type: "Movie", year: "2017" },
  { title: "Letters from Iwo Jima", type: "Movie", year: "2006" },
  { title: "Lethal Weapon", type: "Movie", year: "1987" },
  { title: "Licorice Pizza", type: "Movie", year: "2021" },
  { title: "The Longest Day", type: "Movie", year: "1962" },
  { title: "Love Actually", type: "Movie", year: "2003" },

  { title: "Mad Max: Fury Road", type: "Movie", year: "2015" },
  { title: "Mad Men", type: "TV", year: "2007–2015" },
  { title: "Manchester by the Sea", type: "Movie", year: "2016" },
  { title: "Marcel the Shell with Shoes On", type: "Movie", year: "2021" },
  { title: "Marriage Story", type: "Movie", year: "2019" },
  { title: "Mean Girls", type: "Movie", year: "2004" },
  { title: "Men in Black", type: "Movie", year: "1997" },
  { title: "Midnight in Paris", type: "Movie", year: "2011" },
  { title: "Midway", type: "Movie", year: "2019" },
  { title: "Million Dollar Baby", type: "Movie", year: "2004" },
  { title: "Minari", type: "Movie", year: "2020" },
  { title: "Minority Report", type: "Movie", year: "2002" },
  { title: "Moneyball", type: "Movie", year: "2011" },
  { title: "Moonlight", type: "Movie", year: "2016" },
  { title: "Moonstruck", type: "Movie", year: "1987" },
  { title: "Mrs. Doubtfire", type: "Movie", year: "1993" },
  { title: "Moulin Rouge!", type: "Movie", year: "2001" },

  { title: "Napoleon Dynamite", type: "Movie", year: "2004" },
  { title: "Nightcrawler", type: "Movie", year: "2014" },
  { title: "No Country for Old Men", type: "Movie", year: "2007" },
  { title: "No Time to Die", type: "Movie", year: "2021" },

  { title: "Ocean's Eleven", type: "Movie", year: "2001" },
  { title: "Old School", type: "Movie", year: "2003" },
  { title: "Once Upon a Time in Hollywood", type: "Movie", year: "2019" },
  { title: "Once Upon a Time in the West", type: "Movie", year: "1968" },
  { title: "Oppenheimer", type: "Movie", year: "2023" },
  { title: "The Outlaw Josey Wales", type: "Movie", year: "1976" },
  { title: "Oz", type: "TV", year: "1997–2003" },

  { title: "Palm Springs", type: "Movie", year: "2020" },
  { title: "Parasite", type: "Movie", year: "2019" },
  { title: "Patton", type: "Movie", year: "1970" },
  { title: "Pineapple Express", type: "Movie", year: "2008" },
  { title: "Platoon", type: "Movie", year: "1986" },
  { title: "Poltergeist", type: "Movie", year: "1982" },
  { title: "Poor Things", type: "Movie", year: "2023" },
  { title: "Pretty in Pink", type: "Movie", year: "1986" },
  { title: "Pretty Woman", type: "Movie", year: "1990" },
  { title: "Prisoners", type: "Movie", year: "2013" },
  { title: "Pride & Prejudice", type: "Movie", year: "2005" },
  { title: "Promising Young Woman", type: "Movie", year: "2020" },
  { title: "Pulp Fiction", type: "Movie", year: "1994" },

  { title: "Raging Bull", type: "Movie", year: "1980" },
  { title: "Rain Man", type: "Movie", year: "1988" },
  { title: "Reservoir Dogs", type: "Movie", year: "1992" },
  { title: "Risky Business", type: "Movie", year: "1983" },
  { title: "Rocky", type: "Movie", year: "1976" },
  { title: "Rome", type: "TV", year: "2005–2007" },

  { title: "Saving Private Ryan", type: "Movie", year: "1998" },
  { title: "Saturday Night Fever", type: "Movie", year: "1977" },
  { title: "Schitt's Creek", type: "TV", year: "2015–2020" },
  { title: "Scott Pilgrim vs. the World", type: "Movie", year: "2010" },
  { title: "Seinfeld", type: "TV", year: "1989–1998" },
  { title: "Seven", type: "Movie", year: "1995" },
  { title: "Sex and the City", type: "TV", year: "1998–2004" },
  { title: "The Shawshank Redemption", type: "Movie", year: "1994" },
  { title: "Sherlock", type: "TV", year: "2010–2017" },
  { title: "Sicario", type: "Movie", year: "2015" },
  { title: "Silver Linings Playbook", type: "Movie", year: "2012" },
  { title: "Sleepless in Seattle", type: "Movie", year: "1993" },
  { title: "Spider-Man: Into the Spider-Verse", type: "Movie", year: "2018" },
  { title: "Spider-Man: No Way Home", type: "Movie", year: "2021" },
  { title: "Spirited Away", type: "Movie", year: "2001" },
  { title: "Spotlight", type: "Movie", year: "2015" },
  { title: "Stand by Me", type: "Movie", year: "1986" },
  { title: "Star Wars: A New Hope", type: "Movie", year: "1977" },
  { title: "Stranger Things", type: "TV", year: "2016–" },
  { title: "Succession", type: "TV", year: "2018–2023" },
  { title: "Superbad", type: "Movie", year: "2007" },
  { title: "Super Troopers", type: "Movie", year: "2001" },

  { title: "Taskmaster", type: "TV", year: "2015–" },
  { title: "Ted Lasso", type: "TV", year: "2020–2023" },
  { title: "The Batman", type: "Movie", year: "2022" },
  { title: "The Big Lebowski", type: "Movie", year: "1998" },
  { title: "The Big Short", type: "Movie", year: "2015" },
  { title: "The Big Sick", type: "Movie", year: "2017" },
  { title: "The Bourne Identity", type: "Movie", year: "2002" },
  { title: "The Breakfast Club", type: "Movie", year: "1985" },
  { title: "The Dark Knight", type: "Movie", year: "2008" },
  { title: "The Departed", type: "Movie", year: "2006" },
  { title: "The Devil Wears Prada", type: "Movie", year: "2006" },
  { title: "The Fugitive", type: "Movie", year: "1993" },
  { title: "The Good, the Bad and the Ugly", type: "Movie", year: "1966" },
  { title: "The Good Place", type: "TV", year: "2016–2020" },
  { title: "The Goonies", type: "Movie", year: "1985" },
  { title: "The Grand Budapest Hotel", type: "Movie", year: "2014" },
  { title: "The Green Knight", type: "Movie", year: "2021" },
  { title: "The Hangover", type: "Movie", year: "2009" },
  { title: "The Hurt Locker", type: "Movie", year: "2008" },
  { title: "The Leftovers", type: "TV", year: "2014–2017" },
  { title: "The Life Aquatic with Steve Zissou", type: "Movie", year: "2004" },
  { title: "The Lord of the Rings: The Fellowship of the Ring", type: "Movie", year: "2001" },
  { title: "The Lord of the Rings: The Return of the King", type: "Movie", year: "2003" },
  { title: "The Magnificent Seven", type: "Movie", year: "1960" },
  { title: "The Matrix", type: "Movie", year: "1999" },
  { title: "The Matrix Reloaded", type: "Movie", year: "2003" },
  { title: "The Menu", type: "Movie", year: "2022" },
  { title: "The Night Of", type: "TV", year: "2016" },
  { title: "The Northman", type: "Movie", year: "2022" },
  { title: "The Office (UK)", type: "TV", year: "2001–2003" },
  { title: "The Office (US)", type: "TV", year: "2005–2013" },
  { title: "The Prestige", type: "Movie", year: "2006" },
  { title: "The Princess Bride", type: "Movie", year: "1987" },
  { title: "The Revenant", type: "Movie", year: "2015" },
  { title: "The Shape of Water", type: "Movie", year: "2017" },
  { title: "The Shining", type: "Movie", year: "1980" },
  { title: "The Silence of the Lambs", type: "Movie", year: "1991" },
  { title: "The Sixth Sense", type: "Movie", year: "1999" },
  { title: "The Social Network", type: "Movie", year: "2010" },
  { title: "The Sopranos", type: "TV", year: "1999–2007" },
  { title: "The Sting", type: "Movie", year: "1973" },
  { title: "The Terminator", type: "Movie", year: "1984" },
  { title: "The Texas Chain Saw Massacre", type: "Movie", year: "1974" },
  { title: "The Thin Red Line", type: "Movie", year: "1998" },
  { title: "The Towering Inferno", type: "Movie", year: "1974" },
  { title: "The Truman Show", type: "Movie", year: "1998" },
  { title: "The Unbearable Weight of Massive Talent", type: "Movie", year: "2022" },
  { title: "The White Lotus", type: "TV", year: "2021–" },
  { title: "The Wire", type: "TV", year: "2002–2008" },
  { title: "This Is the End", type: "Movie", year: "2013" },
  { title: "Three Amigos", type: "Movie", year: "1986" },
  { title: "Titanic", type: "Movie", year: "1997" },
  { title: "Top Gun", type: "Movie", year: "1986" },
  { title: "Top Gun: Maverick", type: "Movie", year: "2022" },
  { title: "Tora! Tora! Tora!", type: "Movie", year: "1970" },
  { title: "Toy Story", type: "Movie", year: "1995" },
  { title: "Training Day", type: "Movie", year: "2001" },
  { title: "True Detective", type: "TV", year: "2014–" },
  { title: "True Grit", type: "Movie", year: "1969" },
  { title: "True Lies", type: "Movie", year: "1994" },

  { title: "Unforgiven", type: "Movie", year: "1992" },
  { title: "Up in Smoke", type: "Movie", year: "1978" },

  { title: "Veep", type: "TV", year: "2012–2019" },

  { title: "Wedding Crashers", type: "Movie", year: "2005" },
  { title: "We Were Soldiers", type: "Movie", year: "2002" },
  { title: "West Side Story", type: "Movie", year: "2021" },
  { title: "Whiplash", type: "Movie", year: "2014" },
  { title: "When Harry Met Sally…", type: "Movie", year: "1989" },
  { title: "Zodiac", type: "Movie", year: "2007" }
];
